### ISSUE TITLE
运行时报了Noreturn

### ISSUE THREAD

**Issue by zhaizhijiang** [Dustyposa/rasa_ch_faq#3]
![image](https://user-images.githubusercontent.com/40481760/114655310-8c199a80-9d1e-11eb-8111-49255eef8cd2.png)

**Comment by zhaizhijiang** [comment]
这个是什么原因呢？

**Comment by Dustyposa** [comment]
你的 python 版本是？

**Comment by zhaizhijiang** [comment]
是3.6的

**Comment by Dustyposa** [comment]
3.6 不大清楚
你直接， 我用的 37
你试试 
```python
from typing import NoReturn
```
报错的话你用 37 吧。

**Comment by zhaizhijiang** [comment]
好的
