### ISSUE TITLE
在前端中无法正常问答，该排查哪一部分呢？

### ISSUE THREAD

**Issue by RayShark** [Dustyposa/rasa_ch_faq#4]
运行截图如下
![image](https://user-images.githubusercontent.com/26996377/130576159-a7d39970-b7c6-46da-8fe4-5acee895b940.png)

后端已经开启：
![image](https://user-images.githubusercontent.com/26996377/130576231-de52f1d0-359d-4cf7-8cdd-f1cd33820a30.png)

actions也是开启的：
![image](https://user-images.githubusercontent.com/26996377/130576293-e3ad657c-555e-4f82-aa1a-1bed76e2d945.png)

而且使用rasa shell的话是可以正常问答的，现在就是前端无法回答，想问一下您之前跑的时候遇到过类似的问题吗？

**Comment by Dustyposa** [comment]
排除思路:
1. 开启 `rasa server` 以及 `rasa action` 之后，使用 `curl`  直接访问 `rasa server` 看有没有响应。参考命令：
```bash
curl -X POST  \
  'http://localhost:5005/webhooks/rest/webhook' \
 \
  -d '{
    "sender": "xxxxx",
    "message": "你好"
}'
```
看 `rasa` 本身工作 `ok` 不
2. 在浏览器打开 `F12` 查看网络请求是否正常（是否和 `curl` 一致）

**Comment by RayShark** [comment]
> 排除思路:
> 
> 1. 开启 `rasa server` 以及 `rasa action` 之后，使用 `curl`  直接访问 `rasa server` 看有没有响应。参考命令：
> 
> ```shell
> curl -X POST  \
>   'http://localhost:5005/webhooks/rest/webhook' \
>  \
>   -d '{
>     "sender": "xxxxx",
>     "message": "你好"
> }'
> ```
> 
> 看 `rasa` 本身工作 `ok` 不
> 2. 在浏览器打开 `F12` 查看网络请求是否正常（是否和 `curl` 一致）

我测试了一下，rasa server应该是没问题的，curl的结果是有的：
![image](https://user-images.githubusercontent.com/26996377/130584560-7f8b402a-a8d1-4347-9e15-5a0b3f94cbb1.png)

然后调试浏览器的时候发现无法获取response，CONNECTION REFUSED，估计是我不是从本机访问导致的。
![image](https://user-images.githubusercontent.com/26996377/130584740-60b7ec83-7d0c-4af9-a6fb-da5646f0c260.png)

会不会是因为**不在本机上访问**导致的？
我所有的程序都是部署在服务器上的，前端是用自己的笔记本输入URL打开的，应该是有什么网络配置需要打开（允许外网访问某个端口之类的，或者设置允许的ip，我不太清楚）
我对前端这块实在是不太了解，大神你能说说该怎么解决这个访问限制问题吗。。。
我的服务器系统是Ubuntu 21，内核Linux version 5.11.0-31-generic

**Comment by Dustyposa** [comment]
OK 原因是 `ip` 不同。 在 [这里](https://github.com/Dustyposa/rasa_bot_front/blob/main/src/utils/rasaUtil.js#L4) 更改后端请求地址
前端重新 `build` 即可

**Comment by RayShark** [comment]
> OK 原因是 `ip` 不同。 在 [这里](https://github.com/Dustyposa/rasa_bot_front/blob/main/src/utils/rasaUtil.js#L4) 更改后端请求地址
> 前端重新 `build` 即可

我大概明白了，如果我从自己笔记本的浏览器访问的话，那localhost指向的就是我笔记本的ip，而不是服务器的ip。。。

但是我在后端把ip指定成了服务器的ip之后，console里看ip是对的，可还是无法访问
报错：net::ERR_CONNECTION_TIMED_OUT
![image](https://user-images.githubusercontent.com/26996377/130595162-1f96198b-7518-4243-b311-a2b6b7b25961.png)

我所有服务都按顺序重启了好几遍，不知道是啥原因，linux自带的防火墙吗？

**Comment by RayShark** [comment]
感谢大神的解答，我最后统一使用VS code Remote和Chrome插件运行前后端，这样就解决了无法从另一个ip访问的问题，在调试阶段已经完全够用了~
![image](https://user-images.githubusercontent.com/26996377/130600177-15b14019-f34b-4c78-8bce-59e8902a2d9e.png)

**Comment by Dustyposa** [comment]
> > OK 原因是 `ip` 不同。 在 [这里](https://github.com/Dustyposa/rasa_bot_front/blob/main/src/utils/rasaUtil.js#L4) 更改后端请求地址
> > 前端重新 `build` 即可
> 
> 我大概明白了，如果我从自己笔记本的浏览器访问的话，那localhost指向的就是我笔记本的ip，而不是服务器的ip。。。
> 
> 但是我在后端把ip指定成了服务器的ip之后，console里看ip是对的，可还是无法访问
> 报错：net::ERR_CONNECTION_TIMED_OUT
> ![image](https://user-images.githubusercontent.com/26996377/130595162-1f96198b-7518-4243-b311-a2b6b7b25961.png)
> 
> 我所有服务都按顺序重启了好几遍，不知道是啥原因，linux自带的防火墙吗？

这时候你就可以 尝试使用 `curl` 在前端服务器访问后端服务器进行测试了。 可能是防火墙啥的。
