### ISSUE TITLE
单独 python bert_tokenizer.py 报错，是不是huggingface加载模型方式有变化？

### ISSUE THREAD

**Issue by lizhzh8** [Dustyposa/rasa_ch_faq#5]
rasa train  和rasa shell 都没问题。

![2](https://user-images.githubusercontent.com/30767119/136945888-58a0238f-0982-4379-89fe-fb74c09e5962.png)

**Comment by Dustyposa** [comment]
问题是什么？
rasa train & rasa shell 能运行就是没问题呀。

**Comment by lizhzh8** [comment]
> 问题是什么？ rasa train & rasa shell 能运行就是没问题呀。

我看下来，好像是要在hugging face的库里边的模型才能用。怎么才能用本地自己的模型呢？

**Comment by Dustyposa** [comment]
如果按照这个步骤：[如何从零开始搭建](https://github.com/Dustyposa/rasa_ch_faq#%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E6%90%AD%E5%BB%BA%E6%9C%BA%E5%99%A8%E4%BA%BA)

成功运行，那么就是可以使用本地模型库了。 如何使用，参见 [bert_tokenizer](https://github.com/Dustyposa/rasa_ch_faq/blob/main/compoments/nlu/tokenizers/bert_tokenizer.py)

**Comment by lizhzh8** [comment]
> 如果按照这个步骤：[如何从零开始搭建](https://github.com/Dustyposa/rasa_ch_faq#%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E6%90%AD%E5%BB%BA%E6%9C%BA%E5%99%A8%E4%BA%BA)
> 
> 成功运行，那么就是可以使用本地模型库了。 如何使用，参见 [bert_tokenizer](https://github.com/Dustyposa/rasa_ch_faq/blob/main/compoments/nlu/tokenizers/bert_tokenizer.py)

嗯嗯 ，这些我都运行成功了，也确实能用bert_tokenizer。就是在单个文件 python bert_tokenizer.py 时，用huggingface的模型。我选择了一个小模型，能预测成功。本地模型，我这也成功了，不过模型要用绝对路径。谢谢大佬回复。

**Comment by lizhzh8** [comment]
![image](https://user-images.githubusercontent.com/30767119/137269319-7a2e0685-cdd2-4688-a9ca-fee56aabe82b.png)
